name: edu_link
description: "A new Flutter project."
publish_to: 'none' # This line prevents the package from being accidentally published to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  fluttertoast: ^8.2.5
  latlong2: ^0.9.1
  flutter_osm_plugin: ^0.60.4
  flutter_keyboard_visibility: ^5.2.0
  shared_preferences: ^2.0.13
  font_awesome_flutter: ^10.7.0
  slide_to_act: ^2.0.1
  date_format: ^2.0.6
  cupertino_icons: ^1.0.6
  google_nav_bar: ^5.0.6
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1
  geolocator: ^8.2.0
  path_provider: ^2.1.3
  dio: ^5.5.0+1
  url_launcher: ^6.3.0
  pdf_viewer_plugin: ^2.0.1
  file_picker: ^8.0.5
  image_picker: ^1.1.2
  firebase_storage: ^11.7.7
  dash_chat_2: ^0.0.20
  youtube_player_flutter: ^8.0.0
  flutter_inappwebview: ^5.3.2
  collection: ^1.16.0
  http: ^1.2.1
  provider: ^6.0.3
  flutter_gemini: 2.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  # Example custom fonts section
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700