// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDukQfXnlKnJGGLFQ7vqYL6Jd-lT_hNDBE',
    appId: '1:260570123699:web:75594fbac468793a860fc6',
    messagingSenderId: '260570123699',
    projectId: 'edulink-afb64',
    authDomain: 'edulink-afb64.firebaseapp.com',
    databaseURL: 'https://edulink-afb64-default-rtdb.firebaseio.com',
    storageBucket: 'edulink-afb64.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo6jneuSPicuyDyHK8hyr0RNvCeWLMAmM',
    appId: '1:260570123699:android:01d3f5c11e45f6bc860fc6',
    messagingSenderId: '260570123699',
    projectId: 'edulink-afb64',
    databaseURL: 'https://edulink-afb64-default-rtdb.firebaseio.com',
    storageBucket: 'edulink-afb64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABhfvkrjOSMII3hLOJZYtBq-YpehHyD30',
    appId: '1:260570123699:ios:13c23780fbdc6564860fc6',
    messagingSenderId: '260570123699',
    projectId: 'edulink-afb64',
    databaseURL: 'https://edulink-afb64-default-rtdb.firebaseio.com',
    storageBucket: 'edulink-afb64.appspot.com',
    iosBundleId: 'com.example.eduLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABhfvkrjOSMII3hLOJZYtBq-YpehHyD30',
    appId: '1:260570123699:ios:13c23780fbdc6564860fc6',
    messagingSenderId: '260570123699',
    projectId: 'edulink-afb64',
    databaseURL: 'https://edulink-afb64-default-rtdb.firebaseio.com',
    storageBucket: 'edulink-afb64.appspot.com',
    iosBundleId: 'com.example.eduLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDukQfXnlKnJGGLFQ7vqYL6Jd-lT_hNDBE',
    appId: '1:260570123699:web:dd6b3362b3305a37860fc6',
    messagingSenderId: '260570123699',
    projectId: 'edulink-afb64',
    authDomain: 'edulink-afb64.firebaseapp.com',
    databaseURL: 'https://edulink-afb64-default-rtdb.firebaseio.com',
    storageBucket: 'edulink-afb64.appspot.com',
  );

}